name=Log4j2PropertiesConfig
appenders=console

# Console appender
appender.console.type=Console
appender.console.name=LogToConsole
appender.console.layout=PatternLayout
appender.console.layout.pattern=[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

# By default, put everything in the console and log file
rootLogger.level=debug
rootLogger.appenderRefs=stdout
rootLogger.appenderRef.stdout.ref=LogToConsole

