-- H2 specific code
-- Indexes (performances)
CREATE UNIQUE INDEX PARAMS_PARAM_NAME_IDX    ON PARAMETERS (PARAM_NAME);
CREATE UNIQUE INDEX PARAMS_ACTIVE_PARAM_IDX  ON PARAMETERS (PARAM_NAME, IS_ACTIVE);
