-- H2 specific code
-- Indexes (performances)
CREATE UNIQUE INDEX USERS_USERNAME_IDX          ON USERS (USERNAME);
CREATE UNIQUE INDEX USERS_ACTIVE_USERNAME_IDX   ON USERS (USERNAME, IS_ACTIVE);
CREATE UNIQUE INDEX USERS_EMAIL_IDX             ON USERS (EMAIL);
CREATE UNIQUE INDEX USERS_ACTIVE_EMAIL_IDX      ON USERS (EMAIL, IS_ACTIVE);

