-- UNDO script
DELETE FROM LABELS WHERE CODE IN (
      'HTTP_400_BAD_REQUEST',
      'HTTP_401_UNAUTHORIZED',
      'HTTP_403_FORBIDDEN',
      'HTTP_404_NOT_FOUND',
      'HTTP_500_INTERNAL_SERVER_ERROR'
);